#!/bin/bash

sshfs ecb5@mapes:/home/ecb5/Files2Serve/Videos /home/ecb5/RemoteMounts/Videos
sshfs ecb5@mapes:/home/ecb5/Files2Serve/Music /home/ecb5/RemoteMounts/Music
sshfs ecb5@mapes:/home/ecb5/Files2Serve/Photos /home/ecb5/RemoteMounts/Photos
