(TeX-add-style-hook
 "ExpLog"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "cha:last-elem-funct"
    "eq:x2diffeq"
    "drill:IVP-sqr"
    "sec:exponential"
    "def:natural-exponential-ivp"
    "IVP:ExpDiffeq"
    "eq:ExpDerivs"
    "digress:EffectiveGuessing"
    "eq:ExpSeries1"
    "problem:TaylorSeries1"
    "fig:ExpFifty"
    "eq:ExpSeries2"
    "eq:2^x"
    "eq:d(2^x)"
    "eq:Exp2"
    "eq:Exp3"
    "drill:ComputingE"
    "eq:ExpSeries4"
    "eq:ExpSeries3"
    "eq:ExpApprox"
    "sec:hyperb-trig-hang"
    "problem:HangingChain"
    "eq:CatSol"
    "problem:HyperbolicTrig"
    "problem:SinhCoshDiffeq"
    "fig:GatewayArch"
    "eq:GatewayArch1"
    "eq:GatewayArch2"
    "sec:exponential-growth"
    "example:population-growth"
    "eq:DiscBacterModel"
    "eq:BacteriaIVP"
    "drill:ExpGrowth1"
    "problem:ExpGrowth2"
    "problem:BacteriaIVP1"
    "eq:ExpGen"
    "eq:GeneralExponentialSolution"
    "fig:AlgaeBloomNOAA2"
    "eq:ContinuouslyCompoundedInterest1"
    "eq:ContinuouslyCompoundedInterest2"
    "problem:ContCompound1"
    "sec:natural-logarithm-1"
    "fig:Napier"
    "problem:DoubleYourMoney"
    "drill:BacteriaGuess1"
    "drill:BacteriaGuess2"
    "subsec:radioactive-decay"
    "example:radioactive-dating"
    "IVP:RadioactiveDecay-Wrong"
    "IVP:RadioactiveDecay-Correct"
    "eq:NuclearDecay-Wrong"
    "fig:Libby"
    "fig:ShroudOfTurin"
    "subsec:newtons-law-cooling"
    "eq:CoolingIVP1"
    "eq:UseProp1"
    "eq:NatLogDeriv1"
    "problem:deriv-natur-logar"
    "sec:gener-logar-expon"
    "eq:GenLogConversion"
    "digress:BriggsAndNapier"
    "pic:NapierianLog"
    "eq:GeneralPowerRule"
    "problem:GeneralPowerRule2"
    "problem:LogarithmicDifferentiation1"
    "sec:leonh-euler-harm"
    "eq:SHO6"
    "eq:SHOSpringSolution"
    "eq:DampedOscillator1"
    "eq:DampedProblem1"
    "problem:DampedOscillator1"
    "fig:EulerPortrait"
    "eq:ImagSolution"
    "problem:DampOscExpSol"
    "eq:EulerSimpleSHO-1"
    "problem:DampedOscillation1"
    "problem:EulersFormula"
    "eq:EulerIdentity"))
 :latex)

