(TeX-add-style-hook
 "SlopeVelTan"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "sec:veloc-slop-tang"
    "sec:slopes-tangents"
    "fig:DiffTri"
    "eq:PythTheorDiff"
    "eq:TanLineNoLine"
    "embedded:Deri"
    "sec:defin-tang-line"
    "fig:TangentLineDef6"
    "fig:TangentLineDef7"
    "fig:TangentLineDef5"
    "fig:DiffTri3"
    "def:TangentLine"
    "def:LocalLinearity"
    "problem:tanlinedef"
    "problem:ClassicalCurves1"
    "problem:ClassicalCurves2"
    "digression:DivideByZero"
    "drill:ZeroDenominator1"
    "fig:EllipticCurve2"
    "problem:HyperbolaTriangles"
    "problem:underl-tang-line"
    "sec:vomit-comet"
    "fig:VomitComet"
    "problem:FlightPath2"
    "example:FlightPath"
    "eq:FlightPath"
    "problem:FlightPath1"
    "sec:rates-change"
    "fig:GalileoPortrait"
    "prob:TossedBall1"
    "fig:HammerFeather"
    "eq:Velocity"
    "fig:GalileoTwoNewSciences"
    "problem:PositionVelocityAcceleration"
    "eq:GalileoDiffeq"
    "fig:Pisa1"
    "eq:AccelerationAsSecondDerivative"
    "problem:GeneralFallingBalls"
    "subsec:Derivative"
    "fig:LagrangePortrait"
    "digress:VarConFun2"
    "problem:HuddesRule"
    "eq:PRNotation"
    "example:HighOrderDerivs"
    "problem:NewbyError1"
    "eq:NewbyError1"
    "digression:ProbDiffNotation"
    "sec:newt-flux-dynam"
    "fig:Helicopter3"
    "problem:AirlinerSpeed"
    "fig:Descent2"
    "eq:Descent2"
    "eq:ParFlightPath"
    "sec:newt-meth-flux"
    "fig:Kepler"
    "example:CartPulley"
    "problem:TwoCarts"
    "problem:snell1"
    "fig:SlidingLadder"
    "problem:IdealGas"
    "sec:self-inters-curv"
    "problem:ClassicalCurves3"
    "problem:TschirnhausenCubic"
    "problem:FoliumOfDescartes1"
    "problem:UnitCircleParameterization1"
    "problem:ParametricIVP"
    "fig:Parametric4"
    "sec:bridg-chains-telesc"
    "fig:Bridge7"
    "fig:ChainWithoutBob"
    "fig:HangingChainSchematic"
    "eq:Catenary1"
    "PIC:catenary"
    "eq:CatenaryDiffeq"
    "fig:Pantheon"
    "fig:StPauls"
    "fig:EastRailStation"
    "fig:MountGraham"
    "PIC:SpinCast1"
    "problem:ParabolaDefinition"))
 :latex)

